# Generated by Django 4.2.4 on 2023-08-14 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categroy',
            field=models.CharField(choices=[('1', 'Laptop/SmartGear'), ('2', 'Sound'), ('3', 'Camera'), ('4', 'Game/VR')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='priceMonth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='priceWeek',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empolyee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empolyee')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('startDate', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('empolyee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empolyee')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.product')),
            ],
        ),
    ]
