# Generated by Django 4.2.4 on 2023-08-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscribe', '0002_product_categroy_product_likes_product_pricemonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('startDate', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('empolyee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empolyee')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.product')),
            ],
        ),
    ]
