# Generated by Django 4.2.4 on 2023-08-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscribe', '0003_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='EmpolyeeWishList',
        ),
    ]
