# Generated by Django 4.2.4 on 2023-08-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_rename_wishlist_empolyeewishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
