# Generated by Django 4.2.4 on 2023-08-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_empolyee_schoolcode'),
        ('subscribe', '0005_alter_shopping_count_alter_shopping_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('subscribe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.subscribe')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField()),
                ('reason', models.TextField(max_length=1000)),
                ('empolyee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empolyee')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.product')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateField(auto_now_add=True)),
                ('empolyee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empolyee')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
