# Generated by Django 4.2.4 on 2023-08-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_subscribe_likes_studentwishlist_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='product_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='subscribe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe.subscribe'),
        ),
    ]
