# Generated by Django 4.2.4 on 2023-08-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0007_remove_reservation_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categroy',
            new_name='category',
        ),
    ]
