# Generated by Django 4.2.4 on 2023-08-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0009_subscribe_isallowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='isAllowed',
            field=models.BooleanField(default=False),
        ),
    ]
