# Generated by Django 4.2.4 on 2023-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0011_studentinfo_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
