# Generated by Django 4.2.4 on 2023-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyee',
            name='schoolCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
