# Generated by Django 4.2 on 2023-08-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empolyee_password2_student_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schoolCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
