# Generated by Django 4.2 on 2023-08-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_schoolcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='schoolCode',
        ),
    ]
