# Generated by Django 4.2.4 on 2023-08-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_student_schoolcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='empolyee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
