# Generated by Django 4.2.4 on 2023-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_empolyee_is_active_empolyee_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empolyee',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
