# Generated by Django 4.2.4 on 2023-08-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
